// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mediatr_Extentsion_2026.Commands
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMediatr_Extentsion_2026PackageString = "9c38a80b-0393-4d36-9d9c-ddb83b52f4ee";
        public static Guid guidMediatr_Extentsion_2026Package = new Guid(guidMediatr_Extentsion_2026PackageString);

        public const string guidMediatr_Extentsion_2026PackageCmdSetString = "0275377e-db6f-4b7f-83d8-089572a36488";
        public static Guid guidMediatr_Extentsion_2026PackageCmdSet = new Guid(guidMediatr_Extentsion_2026PackageCmdSetString);

        public const string guidImagesString = "4d598310-e0d6-4684-9ff6-c99c6a6e4d3a";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AddMediatRItemCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
